### ISSUE TITLE
关于建立连接的疑问

### ISSUE THREAD

**Issue by yinft** [anlingyi/xechat#5]
![image](https://user-images.githubusercontent.com/34081792/102177769-27207600-3edf-11eb-9079-5e28167d1d3a.png)
请问新建连接的时候，这个username和avatar字段前端我没找到在哪里有传啊？
还有就是连接建立成功的时候返回的user-name字段名又是从哪里来的？期待回复

**Comment by anlingyi** [comment]
**问题一**

用户信息是前端通过调用一个叫 `createUser()` 方法构建的一个 `Json` 字符串，然后再将此 `Json` 信息作为本次连接的请求头的。

<img width="634" alt="截屏2020-12-15 下午11 41 05" src="https://user-images.githubusercontent.com/38127688/102238939-4cd66b00-3f31-11eb-8946-7a3b4e3392c9.png">

<img width="643" alt="截屏2020-12-15 下午11 46 33" src="https://user-images.githubusercontent.com/38127688/102239431-d1c18480-3f31-11eb-804e-962a8ff71efa.png">

后端通过一个叫 `WebSocketInterceptor` 的拦截器，拦截连接请求，将请求头中的用户信息拿出来，然后绑定到 `User` 对象中。

<img width="1144" alt="截屏2020-12-15 下午11 49 37" src="https://user-images.githubusercontent.com/38127688/102239397-c706ef80-3f31-11eb-9f55-4ed8b6a4a3d0.png">

**问题二**

`user-name` 字段在连接成功后会由框架本身返回的，它的值是通过 `User` 对象的 `getName()` 方法决定的，`getName()` 方法来源于 `Principal` 接口，我是将 `userId` 返回给它。

<img width="654" alt="截屏2020-12-15 下午11 50 32" src="https://user-images.githubusercontent.com/38127688/102240510-e8b4a680-3f32-11eb-970f-61f3d146c757.png">
